"""
LLM-Based Judge for Answer Quality Evaluation

Provides an LLM judge that evaluates whether generated answers are similar to
ground truth answers, useful for complementing automatic metrics like F1 and ROUGE-L.

The judge can provide:
- Semantic similarity judgments
- Relevance assessment
- Coverage of key facts
- Reasoning explanations
"""

import asyncio
import logging
import time
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Tuple, Optional

import openai
import tiktoken

from .data_models import RetrievalResult
from .prompts import PromptRegistry

logger = logging.getLogger(__name__)


class BaseJudge(ABC):
    """Abstract base class for answer judges."""

    def __init__(self, model: str = "gpt-4o-mini", temperature: float = 0.0):
        """
        Initialize judge.

        Args:
            model: Model name/identifier
            temperature: Sampling temperature (low for consistency)
        """
        self.model = model
        self.temperature = temperature

    @abstractmethod
    async def judge_answer_similarity(
        self,
        question: str,
        generated_answer: str,
        ground_truth_answers: List[str]
    ) -> Dict[str, Any]:
        """
        Judge if generated answer is similar to ground truth answers.

        Args:
            question: The original question
            generated_answer: Answer generated by the system
            ground_truth_answers: List of valid ground truth answers

        Returns:
            {
                "similarity_score": float (0-1),
                "is_similar": bool,
                "reasoning": str,
                "matched_answer": Optional[str],  # Which ground truth it matched
                "coverage_score": float (0-1),
                "coverage_reasoning": str,
                "generation_time": float,
                "total_tokens": int
            }
        """
        pass

    @abstractmethod
    async def judge_disambiguation(
        self,
        question: str,
        generated_answer: str,
        ground_truth_interpretations: List[Dict[str, Any]],
        dataset: str = "ambignq"
    ) -> Dict[str, Any]:
        """
        Judge if answer addresses all interpretations of an ambiguous question.

        Args:
            question: The ambiguous question
            generated_answer: Generated answer
            ground_truth_interpretations: List of ground truth interpretations
                For AmbigNQ: list of answer sets
                For ASQA: list of qa_pairs with questions and short_answers
            dataset: "ambignq" or "asqa"

        Returns:
            {
                "disambiguation_score": float (0-1),
                "interpretations_covered": int,
                "total_interpretations": int,
                "covered_interpretations": List[int],  # indices
                "missing_interpretations": List[int],
                "reasoning": str,
                "generation_time": float,
                "total_tokens": int
            }
        """
        pass

    @abstractmethod
    async def judge_long_form_answer(
        self,
        question: str,
        generated_answer: str,
        reference_answer: str
    ) -> Dict[str, Any]:
        """
        Judge long-form answer quality (for ASQA).

        Args:
            question: The question
            generated_answer: Generated long-form answer
            reference_answer: Reference long-form answer

        Returns:
            {
                "quality_score": float (0-1),
                "factuality": float (0-1),
                "completeness": float (0-1),
                "coherence": float (0-1),
                "reasoning": str,
                "generation_time": float,
                "total_tokens": int
            }
        """
        pass


class OpenAIJudge(BaseJudge):
    """OpenAI-based answer judge."""

    def __init__(
        self,
        model: str = "gpt-4o-mini",
        temperature: float = 0.0,
        api_key: Optional[str] = None
    ):
        """Initialize OpenAI judge."""
        super().__init__(model=model, temperature=temperature)
        self.api_key = api_key
        if api_key:
            openai.api_key = api_key

    async def judge_answer_similarity(
        self,
        question: str,
        generated_answer: str,
        ground_truth_answers: List[str]
    ) -> Dict[str, Any]:
        """Judge if generated answer is similar to ground truth answers."""
        
        start_time = time.time()
        
        # Format ground truth list
        gt_str = "\n".join(f"{i+1}. {ans}" for i, ans in enumerate(ground_truth_answers))
        
        prompt = f"""You are an expert judge evaluating question-answering systems.

Question: {question}

Generated Answer: {generated_answer}

Ground Truth Answers (any one is acceptable):
{gt_str}

Task: Determine if the generated answer is semantically similar to ANY of the ground truth answers.

Consider:
1. Does the generated answer convey the same meaning/facts as at least one ground truth answer?
2. Is the information correct and not contradictory?
3. Does it adequately answer the question?

Respond in JSON format:
{{
    "similarity_score": <float 0-1 indicating semantic similarity>,
    "is_similar": <boolean>,
    "matched_answer": "<which ground truth answer was matched, or null>",
    "reasoning": "<explain your judgment>",
    "coverage_score": <float 0-1 for fact coverage>,
    "coverage_reasoning": "<explain coverage>"
}}"""

        try:
            response = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: openai.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=self.temperature,
                    response_format={"type": "json_object"}
                )
            )
            
            response_text = response.choices[0].message.content
            tokens = response.usage.total_tokens
            
            import json
            result = json.loads(response_text)
            
            return {
                **result,
                "generation_time": time.time() - start_time,
                "total_tokens": tokens
            }
        except Exception as e:
            logger.error(f"OpenAI judge error: {e}")
            return {
                "similarity_score": 0.0,
                "is_similar": False,
                "matched_answer": None,
                "reasoning": f"Judge error: {str(e)}",
                "coverage_score": 0.0,
                "coverage_reasoning": "Error in judging",
                "generation_time": time.time() - start_time,
                "total_tokens": 0,
                "error": str(e)
            }

    async def judge_disambiguation(
        self,
        question: str,
        generated_answer: str,
        ground_truth_interpretations: List[Dict[str, Any]],
        dataset: str = "ambignq"
    ) -> Dict[str, Any]:
        """Judge if answer addresses all interpretations."""
        
        start_time = time.time()
        
        # Format interpretations based on dataset
        if dataset == "asqa":
            # ASQA format: list of qa_pairs with questions and short_answers
            interp_str = "\n".join(
                f"{i+1}. Question: {qa.get('question', '')}\n"
                f"   Valid Answers: {', '.join(qa.get('short_answers', []))}"
                for i, qa in enumerate(ground_truth_interpretations)
            )
        else:
            # AmbigNQ format: list of answer sets (qa_pairs with question and short_answers)
            interp_str = "\n".join(
                f"{i+1}. Question: {qa.get('question', '')}\n"
                f"   Valid Answers: {', '.join(qa.get('short_answers', []))}"
                for i, qa in enumerate(ground_truth_interpretations)
            )
        
        prompt = f"""You are an expert judge evaluating disambiguation coverage.

Ambiguous Question: {question}

Generated Answer: {generated_answer}

Interpretations of this question (each represents a valid distinct meaning):
{interp_str}

Task: For EACH interpretation, determine if the generated answer provides information 
that would satisfy that specific interpretation by matching at least one of the valid answers.

IMPORTANT: An interpretation is "covered" ONLY if:
1. The generated answer contains information that matches or directly answers the specific question for that interpretation, AND
2. The answer matches semantically with at least one of the valid answers listed for that interpretation

For example, if interpretation #3 asks "What year was the movie released?" and the valid answers are "2002, 2005", then the generated answer must explicitly provide one of those years (or equivalent semantic meaning) to be marked as "covered" for that interpretation.

Do NOT mark an interpretation as covered just because the generated answer is generally related to the topic.

Respond in JSON format:
{{
    "total_interpretations": {len(ground_truth_interpretations)},
    "interpretations_covered": <int: how many interpretations are actually covered by the answer>,
    "covered_interpretations": [<list of 0-indexed interpretation numbers that are covered>],
    "missing_interpretations": [<list of 0-indexed interpretation numbers that are NOT covered>],
    "per_interpretation_analysis": [
        {{"index": 0, "is_covered": <bool>, "required_answer": "<what answer was needed for this interpretation>", "generated_content": "<what the generated answer said about this>", "reasoning": "<explain why it does or does not cover this interpretation>"}},
        ...
    ],
    "overall_reasoning": "<overall explanation of coverage - note which interpretations were missed and why>"
}}"""

        try:
            response = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: openai.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=self.temperature,
                    response_format={"type": "json_object"}
                )
            )
            
            response_text = response.choices[0].message.content
            tokens = response.usage.total_tokens
            
            import json
            result = json.loads(response_text)
            
            # Calculate score
            score = result.get("interpretations_covered", 0) / max(1, result.get("total_interpretations", 1))
            
            return {
                **result,
                "disambiguation_score": score,
                "reasoning": result.get("overall_reasoning", ""),
                "generation_time": time.time() - start_time,
                "total_tokens": tokens
            }
        except Exception as e:
            logger.error(f"OpenAI disambiguation judge error: {e}")
            return {
                "total_interpretations": len(ground_truth_interpretations),
                "interpretations_covered": 0,
                "covered_interpretations": [],
                "missing_interpretations": list(range(len(ground_truth_interpretations))),
                "disambiguation_score": 0.0,
                "reasoning": f"Judge error: {str(e)}",
                "generation_time": time.time() - start_time,
                "total_tokens": 0,
                "error": str(e)
            }

    async def judge_long_form_answer(
        self,
        question: str,
        generated_answer: str,
        reference_answer: str
    ) -> Dict[str, Any]:
        """Judge long-form answer quality (for ASQA)."""
        
        start_time = time.time()
        
        prompt = f"""You are an expert judge evaluating long-form answer quality.

Question: {question}

Generated Answer:
{generated_answer}

Reference Answer:
{reference_answer}

Task: Evaluate the generated answer across multiple dimensions.

Consider:
1. Factuality: Are the facts correct and supported?
2. Completeness: Does it cover the key points from the reference?
3. Coherence: Is it well-organized and easy to follow?

Respond in JSON format:
{{
    "quality_score": <float 0-1 overall quality>,
    "factuality": <float 0-1, correctness of facts>,
    "completeness": <float 0-1, coverage of key points>,
    "coherence": <float 0-1, organization and clarity>,
    "reasoning": "<explain your judgments>",
    "key_strengths": ["<strength1>", "<strength2>"],
    "key_weaknesses": ["<weakness1>", "<weakness2>"]
}}"""

        try:
            response = await asyncio.get_event_loop().run_in_executor(
                None,
                lambda: openai.chat.completions.create(
                    model=self.model,
                    messages=[{"role": "user", "content": prompt}],
                    temperature=self.temperature,
                    response_format={"type": "json_object"}
                )
            )
            
            response_text = response.choices[0].message.content
            tokens = response.usage.total_tokens
            
            import json
            result = json.loads(response_text)
            
            return {
                **result,
                "generation_time": time.time() - start_time,
                "total_tokens": tokens
            }
        except Exception as e:
            logger.error(f"OpenAI long-form judge error: {e}")
            return {
                "quality_score": 0.0,
                "factuality": 0.0,
                "completeness": 0.0,
                "coherence": 0.0,
                "reasoning": f"Judge error: {str(e)}",
                "key_strengths": [],
                "key_weaknesses": ["Evaluation failed"],
                "generation_time": time.time() - start_time,
                "total_tokens": 0,
                "error": str(e)
            }


class CachedJudge:
    """Wrapper around judge with result caching to avoid redundant API calls."""
    
    def __init__(self, judge: BaseJudge):
        """Initialize cached judge."""
        self.judge = judge
        self.cache = {}
    
    def _make_cache_key(self, judgment_type: str, *args) -> str:
        """Create cache key from judgment type and arguments."""
        import hashlib
        key_str = f"{judgment_type}:" + "|".join(str(arg) for arg in args)
        return hashlib.md5(key_str.encode()).hexdigest()
    
    async def judge_answer_similarity(
        self,
        question: str,
        generated_answer: str,
        ground_truth_answers: List[str]
    ) -> Dict[str, Any]:
        """Judge with caching."""
        cache_key = self._make_cache_key("similarity", question, generated_answer, tuple(ground_truth_answers))
        
        if cache_key in self.cache:
            logger.debug(f"Cache hit for similarity judgment")
            return self.cache[cache_key]
        
        result = await self.judge.judge_answer_similarity(question, generated_answer, ground_truth_answers)
        self.cache[cache_key] = result
        return result
    
    async def judge_disambiguation(
        self,
        question: str,
        generated_answer: str,
        ground_truth_interpretations: List[Dict[str, Any]],
        dataset: str = "ambignq"
    ) -> Dict[str, Any]:
        """Judge with caching."""
        cache_key = self._make_cache_key("disambiguation", question, generated_answer, tuple(str(i) for i in ground_truth_interpretations))
        
        if cache_key in self.cache:
            logger.debug(f"Cache hit for disambiguation judgment")
            return self.cache[cache_key]
        
        result = await self.judge.judge_disambiguation(question, generated_answer, ground_truth_interpretations, dataset)
        self.cache[cache_key] = result
        return result
    
    async def judge_long_form_answer(
        self,
        question: str,
        generated_answer: str,
        reference_answer: str
    ) -> Dict[str, Any]:
        """Judge with caching."""
        cache_key = self._make_cache_key("long_form", question, generated_answer, reference_answer)
        
        if cache_key in self.cache:
            logger.debug(f"Cache hit for long-form judgment")
            return self.cache[cache_key]
        
        result = await self.judge.judge_long_form_answer(question, generated_answer, reference_answer)
        self.cache[cache_key] = result
        return result
    
    def get_stats(self) -> Dict[str, int]:
        """Get cache statistics."""
        return {
            "cache_size": len(self.cache),
            "cached_judgments": len(self.cache)
        }
